# Generated by Django 4.2.11 on 2024-04-29 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255)),
                ('product_dimension', models.CharField(blank=True, max_length=255)),
                ('date_first_available', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('asin', models.CharField(blank=True, max_length=255, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('origin_country', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('packer', models.CharField(blank=True, max_length=255)),
                ('importer', models.CharField(blank=True, max_length=255)),
                ('item_weight', models.CharField(blank=True, max_length=255)),
                ('item_dimension', models.CharField(blank=True, max_length=255)),
                ('net_quantity', models.CharField(blank=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('url', models.URLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=255)),
                ('total_rating', models.CharField(blank=True, max_length=255)),
                ('product_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.productdetails')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.userdetail'),
        ),
    ]
