# Generated by Django 5.0.4 on 2024-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
