# Generated by Django 5.0.4 on 2024-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdetails_date_first_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='asin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
