# Generated by Django 5.0.4 on 2024-04-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdetails_asin_alter_userdetail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'failed')], max_length=200)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_email', to='product.emailnotification')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notified', to='product.userdetail')),
            ],
        ),
    ]
